name: Ruff
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Run Ruff and auto-fix
        run: |
          pip install ruff
          ruff check . --fix
          ruff format .
      - name: Create Pull Request with Ruff fixes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "style: auto-fix with ruff"
          title: "style: auto-fix with ruff"
          body: "This PR applies automatic code style fixes using Ruff."
        #   branch: ${{ github.head_ref }}
          base: ${{ github.head_ref }}
          delete-branch: false